### ISSUE TITLE
Phantom X (A) button press on ROG Ally X

### ISSUE THREAD

**Issue by memmam** [hhd-dev/hhd#109]
Hello!

I have a ROG Ally X, on which I've installed Nobara and the ROG Ally / Ally X-specific kernel found at https://github.com/jlobue10/ALLY_Nobara_stuff. I've uninstalled the included inputplumber installation and replaced it with HHD.

My problem is, when I press the Armoury Crate button, it seems to produce phantom button presses.

One press, and it presses X (A) on whatever screen I'm on before it brings up the QAM.

~~Two presses, and it does the above behavior, and then also seems to press X (A) _again_ in the HHD menu, usually opening the TDP menu.~~ Edit: this specific behavior has stopped happening for me and I'm not sure why, maybe I was accidentally pressing more than twice, as pressing the Armoury Crate button while in the HHD menu seems to act as an X (A) press. The previously mentioned behavior with one press is still present.

Checking with the Steam Big Picture controller tester, it looks like what it's doing is trying to simulate a button combo (PS + X / Guide + A), but instead it's doing X + PS + X (A + Guide + A) instead. Turning on 'Switch ROG and Menu/View' switches the buttons as intended, so now the button above the Armoury Crate button opens the QAM without issues, but the phantom X (A) button press stays on the Armoury Crate button, which now performs Start + X (Start + A) instead of just Start.

I'm not sure if this is a problem with HHD or with my specific setup, but I can't find a community Discord or any other support mechanism for HHD, and I can't find any relevant settings looking at the config file, so I'm opting to post here hoping that my issue can be fixed, and if it's a deeper issue with HHD, it can be fixed for others.

Thank you! If there's any other information I can or should provide, please let me know; I'll be watching this issue for any replies.

**Comment by antheas** [comment]
If you want to use nobara, use [this kernel](https://github.com/hhd-dev/linux-bazzite), remove hhd from dnf, and install either the copr or local install variants from here.

Also, the kernel above uses a new kernel patch that automatically selects the correct Ally speaker firmware, so you will want to make sure your linux-firmware is up to date, in case GE messes with that too.

Otherwise, nobara is unfortunately unsupported.

**Comment by antheas** [comment]
You are right though, I need to stick a discord link somewhere.

**Comment by memmam** [comment]
Switching kernels did in fact fix the button press issue, but now I don't have any audio. Nobara reports linux-firmware as version 20240909-1.fc40.noarch.

I found the list of firmware files contained within linux-firmware on git.kernel.org. Can you specify which firmware file I need?

**Comment by antheas** [comment]
You need the Linux firmware that came last week, 17.

Otherwise https://gitlab.com/kernel-firmware/linux-firmware/-/commit/4cbaca8d279c5b37dc999e9e6b9a5d8c3cbad2f5

**Comment by antheas** [comment]
Place on /usr/lib/firmware not in a subdir

**Comment by memmam** [comment]
Can confirm all issues are solved after copying those two files! It IS a shame that I had to switch away from the kernel I was using, as it contained Zen 4-specific link-time optimizations, which I assume this Bazzite kernel lacks, but c'est la vie.

Thank you for your assistance. :)

**Comment by antheas** [comment]
The bazzite kernel ships with sched ext and BORE, so even though it does not use LTO it will be better.

As for LTO, there are not many benchmarks showing that it's better and it makes compilation take 3x longer.

**Comment by memmam** [comment]
Fair enough! Thank you again for your assistance, and sorry for hassling you about this.

**Comment by memmam** [comment]
@antheas for future reference, I ended up having new, worse, unexplained problems with HHD gradually cropping up out of nowhere, I'm just biting the bullet and switching to Bazzite even though I was trying to avoid it. I think it's safe to say Nobara is like, mega super turbo unsupported.

**Comment by antheas** [comment]
Would be good to list them.

**Comment by memmam** [comment]
> Would be good to list them.

Okay so issues I ran into not documented already in this ticket are:

1. Nobara insists on reinstalling the included Decky plugins on reboot. This includes SimpleDeckyTDP, which is incompatible with HHD. This can be resolved by removing SimpleDeckyTDP from `/usr/share/deckyloader` in addition to from `~/homebrew`.
2. I stopped being able to use the B button to back out of the Steam keyboard from within Desktop Mode, for some reason?
3. After a while my button bindings got really messed up (Triangle became Square, L1 became Triangle, Start seems unbound entirely, probably other things I haven't noticed)
4. This may have been intended behavior / user error, but when I reinstalled HHD and switched kernels, shortcut support unchecked itself which was frustrating until I figured it out

**Comment by antheas** [comment]
4) I think nobara force reinstalls inputplumber every time you update, and maybe removed hhd

For 1-3, ack. Seem unrelated though.

Ok so its safe to call nobara unsupported moving forward.

**Comment by memmam** [comment]
2 and 3 only started after switching kernels, so I think it's safe to say that since HHD has issues both with the Nobara kernel and the Bazzite kernel, yeah, probably wise.

Ideally if you could solve the phantom button input issue with the Nobara kernel it'd be fine, but that seems spectacularly out-of-scope.

**Comment by antheas** [comment]
Got my numbers confused, its probably inputplumber, it would not just do SimpleDeckyTDP.

**Comment by memmam** [comment]
Just checked with dnf and it reports inputplumber is still uninstalled. I'm not blaming the Bazzite kernel but something about switching to the Bazzite kernel has made Nobara+HHD _very_ angry, if I thought it was a Bazzite kernel issue I wouldn't be planning to switch to Bazzite + the kernel you linked.

**Comment by antheas** [comment]
My Ally X is currently on Bazzite and I do most of my dev work on Bazzite now.

I cant tell you what caused what you are experiencing (without logs; `journalctl -b | fpaste`) and perhaps its not worth finding out either.

**Comment by memmam** [comment]
Agreed, just wanted to make you aware of it before I nuke my Nobara install into the dirt and install Bazzite so you can tell people in the future not to bother. I don't think diagnosing this further is really worth either of our time.
