### ISSUE TITLE
Handle when acpi_call is available, without r/w permissions

### ISSUE THREAD

**Issue by waffleabyssx0x** [hhd-dev/hhd#112]
When HHD is run in devices such as the Lenovo Legion Go which require `acpi_call` module to set TDP values, please add code to check whether HHD has sufficient permissions to rw `/proc/acpi/call`. The current state of the software will cause an error thrown by `adjustor` only whenever `/proc/acpi/call` is used, but it would be better to add a warning on HHD startup by figuring out whether the file permissions and the process HHD is running as will allow rw access to the file.

**Comment by antheas** [comment]
There is already a warning if acpi call is not detected. All functionality in adjustor expects to be run as root so I don't know if there is a point to this.
