### ISSUE TITLE
`readme.md` link to `github.com/hhd-dev/bmi260` is parsed wrongly by github.com. Maybe use complete URL with protocol?

### ISSUE THREAD

**Issue by dreirund** [hhd-dev/hhd#28]
The file [`readme.md`](https://github.com/hhd-dev/hhd/blob/master/readme.md#L228) has a link to the URL `github.com/hhd-dev/bmi260`:

> ```markdown
> To use the gyro, you will need a [dkms package](github.com/hhd-dev/bmi260)
> for the Bosch 260 IMU Driver.
> ```

The URL [`https://github.com/hhd-dev/bmi260`](https://github.com/hhd-dev/bmi260) (note that `https://` is prepended by me or my browser, it does not come from your URL) works, but when [viewing the `readme.md` in github.com](https://github.com/hhd-dev/hhd/blob/master/readme.md) that URL is converted to [`https://github.com/hhd-dev/hhd/blob/master/github.com/hhd-dev/bmi260`](https://github.com/hhd-dev/hhd/blob/master/github.com/hhd-dev/bmi260) which leads to a non-existing page (HTTP error "404 not found").

I think you should either prefix `https://` to or remove `github.com` from your URL.

Regards!

**Comment by antheas** [comment]
Thanks for noticing!
