### ISSUE TITLE
[request] winmax 2 2022 support

### ISSUE THREAD

**Issue by eugenov** [hhd-dev/hhd#32]
Hello!
Are you planning to add GPD Winmax2 2022 to compatible devices list (Bosch 160)?
Thanks

**Comment by antheas** [comment]
Next major version will add experimental compatibility for all gpd win devices. Should be in a week or so

However, there are still potential issues such as misaligned gyro axis and buttons

You can find us on discord in the ChimeraOS, bazzite, or gpd servers. If you join I can add a configuration for your device so that it is properly supported

**Comment by antheas** [comment]
The Bosch 160 IMU situation is still a bit messy depending in how it is configured in your device's bios

Regardless, if it is broken there's a simple fix for it. However it is not currently packaged for any current kernel/distribution

**Comment by antheas** [comment]
No, it's a one line change in the bmi160 driver to enable your bios entry

The reason it is not upstream is because of politics

You can find it here. Note that this package is outdated and will not install. But the fix still works.
https://github.com/pastaq/bmi160-aya-neo

**Comment by NightHammer1000** [comment]
I don't think so as its a driver Issue.

**Comment by antheas** [comment]
It seems that the bmi160 patch is now part of bazzite and experimental support for unsupported devices is part of hhd too now.

So, it's time to check out your device so we can add support for it. You are the first one with an older model so hopefully it works.

Heres how to find the gyro axis.
https://github.com/hhd-dev/hhd?tab=readme-ov-file#-finding-the-correct-axis-for-your-device

**Comment by antheas** [comment]
Sure, if you don't want to test your device under hhd

**Comment by antheas** [comment]
So, does the Winmax 2022 work at the end?

**Comment by antheas** [comment]
You did not post any logs to help me see why it is not supported but in any case, closing.
