### ISSUE TITLE
Legion Go : touch screen doesn't work when game are runing

### ISSUE THREAD

**Issue by HarAakRanaud** [hhd-dev/hhd#38]
in many games  when i need to use the touch screen (miniMetro, Civilisation 5, VRChat) it doesn't work

sometime a cursor appears but no always i can't click when a game is runing.

i don't know if it's an probleme from HHD or my setup on my the legion go

if it can help i have made a vidéo of the issue
https://youtu.be/2wdDfE5XYbs

**Comment by antheas** [comment]
Hi Har,
This is completely unrelated to hhd but I will not close the issue yet.

What os are you running?

The touch gestures are not provided by hhd, but by a modified version of gamescope.

**Comment by HarAakRanaud** [comment]
i use NobaraOs

**Comment by matte-schwartz** [comment]
> i use NobaraOs

Was it working until recently or has this always not worked for you? The only package updated in the past couple days was Gamescope, so if this just popped up, can you confirm whether or not the problem persists after `sudo dnf downgrade gamescope` to test the previous Gamescope version.

**Comment by HarAakRanaud** [comment]
this always not worked, i have try sudo dnf downgrade gamescope but this issue are always here.

**Comment by matte-schwartz** [comment]
> this always not worked, i have try sudo dnf downgrade gamescope but this issue are always here.

I don’t have a device to test this stuff myself. Does the touchscreen work as expected if you launch games from desktop? The sliding gestures won’t work but that’s normal.

**Comment by antheas** [comment]
It should be the same on all devices. It might be related to the recent gamescope patch for the gestures.

**Comment by HarAakRanaud** [comment]
> It should be the same on all devices. It might be related to the recent gamescope patch for the gestures. Or it might be just gamescope being gamescope


i have downgrade the gamescope but the issue is always here

**Comment by matte-schwartz** [comment]
It is a problem with the steam input preset you are using. Change to a different controller layout with steam input by toggling “show all devices” and try a community layout made for Steam Deck.

**Comment by antheas** [comment]
Problem was found. I'm also getting this bug now, hella annoying.
