### ISSUE TITLE
Turn On/Off automatically on exit/enter game mode

### ISSUE THREAD

**Issue by Tekkenfede** [hhd-dev/hhd#44]
On Gpd win mini I'm obliged to open the UI and disable emulation(decky or desktop) to make work again the touchpad in desktop mode with gestures(that on a similar device means using it like a normal device)

Is it eventually possible to add a toggle to make possible an automatic on/off like said in the title?
Cause in gamemode having touchpad emulation (controller or virtual) is the only way to have an effective left click from the touchpad.(while it messes up things on the desktop)

Ps: I'm on bazzite

**Comment by antheas** [comment]
I hope to to this as part of per-game profiles but I will try to think of a way to do this before hand.

The issue right now is that I dont know if you are in gamemode or not but that will change soon.

It will just take a bit of time. Doesn't the Win Mini have a touchpad click?

**Comment by antheas** [comment]
Yep, just wondering if you could go by by disabling it all the time

But now I recall that the win max is the one that also clicks

**Comment by Tekkenfede** [comment]
Yeah, in both cases I can open and use without any problem the electron UI to disable it.
Or just use controller commands/touch in decky.
It's just the classic "feature" I would like to see automated if the user wants to.(no hurry/priority, just my 2 cents on a niche device ahah)

**Comment by antheas** [comment]
https://github.com/hhd-dev/hhd/releases/tag/v2.5.0
https://github.com/hhd-dev/hhd/commit/6cb10213cdd9ae465694b7234cf8b2cf4c736016

Enjoy.

**Comment by Tekkenfede** [comment]
Tried today! Thanks a lot, it also seems to disable/enable on the go if you set steam input in desktop mode, something really cool.(Dunno if expected, but in the worst case, nice bug ahaha)
