### ISSUE TITLE
hhd systemd service should backoff when device not found

### ISSUE THREAD

**Issue by fishman** [hhd-dev/hhd#47]
I have a GPD win max2 and I tend to disable it before sleep. Unfortunately hhd will just keep retrying finding the device every second until it's back. There should be a better way for it to look for the device.

**Comment by antheas** [comment]
What and why do you disable it?

Already, hhd will look for the device being in mouse mode and wait. This can be expanded.

**Comment by antheas** [comment]
Closed due to inactivity.
