### ISSUE TITLE
[Fedora] add dependencies to install manual

### ISSUE THREAD

**Issue by eugenov** [hhd-dev/hhd#58]
Hello!
After installing hhd fron dnf, hhd does not start - it require additional packages: hidapi and acpi_call.
hidapi is available in repos, but acpi_call exists only in third-party repos or here https://github.com/MiMillieuh/acpi_call-fedora

**Comment by antheas** [comment]
Sure thing
https://github.com/hhd-dev/hhd/commit/aca9e65a6e4690c05acd54dcb408eea6c92a8d79
https://github.com/hhd-dev/hhd/commit/12ab2712d0eb5e3f9794b205560a476bfdf70c53

**Comment by PingPongLee** [comment]
I would like to request that this is looked upon again. After following the installation steps, and starting the UI on Fedora 43, i f i go to TDP Controls, and click "Enable TDP Controls" i get an error box below the button saying "Error Can not write to 'acpi_call'. It is required for TDP."

**Comment by antheas** [comment]
Unfortunately there is no provides for acpi call in fedora. Can you point me to a package for it?

**Comment by eugenov** [comment]
I used that one
https://github.com/MiMillieuh/acpi_call-fedora/releases/download/1.2.2-1/acpi_call-1.2.2-1.x86_64.rpm

**Comment by antheas** [comment]
If I add that as a dependency it won't install. If you want you can provide a spec rpm repo that we can build on the hhd-dev/hhd copr

However it will be an optional dependency because your kernel might provide it
