### ISSUE TITLE
[Question] Does hhd-ui work only in gamescope with wp_presentation?

### ISSUE THREAD

**Issue by bakamomi** [hhd-dev/hhd#64]
I noticed this line in logs:
```
Could not find overlay displays, gamescope is not active.
```
It explains why hdd-ui doesn't launch in kwin when I press the hotkey, but the hotkey doesn't work even in games launched with gamescope. Is it because it requires wp_presentation? Plasma 5 doesn't support it.
```
Your Wayland compositor does NOT support wp_presentation/presentation-time which is required for VK_KHR_present_wait and VK_KHR_present_id.
```

**Comment by antheas** [comment]
If you followed the local install steps, they're currently missing the desktop shortcut. You can launch the desktop version with the command hhd-ui, and shortcut it as you wish

The overlay feature is hardcoded to work in gamescope. Wayland especially does not let us reposition windows, so it does not make much sense to try to port this functionality there, but it is a WIP. It would be nice to open the app with a double tap

**Comment by antheas** [comment]
Also when saying gamescope, I mean steam + gamescope. The overlay launches in the Wayland display that houses steam and only exists if steam integration is activate

The overlay will also not be launched if steam is not detected

**Comment by antheas** [comment]
When you use gamescope with steam support enabled, it launches 2 XWayland instances, puts the overlays in the first instance, and then steam launches and manages games on the second instance. Then when steam needs to appear, it flicks some switches in Gamescope, and gamescope renders it on top.

There is a reason Valve did this this way, it is the only way to have an overlay that works 100% of the time. If you used steam in desktop you'd notice the steam overlay is almost unusable.

The Handheld Daemon overlay pretends to be steam, and boots steam out when it needs to appear. It is done in such a way where you can not tell it is happening. However, as a result, the overlay only works when steam is running. If you launch gamescope with steam integration without steam it will not work. You will just get a black screen.

Of course, with extra dev time, you could launch the hhd command with gamescope and it would do the orchestration. However, you are the first one to ask, and it is a big feature.

**Comment by antheas** [comment]
Turns out I was partly wrong and you can abuse gamescope a bit to get the overlay working. Also, as of 3.0, the button will work in KDE as well.

https://github.com/hhd-dev/hhd/commit/586b3643ce821fa98d2c80f8248d0652720bec2e
https://github.com/hhd-dev/hhd/releases/tag/v3.1.0
