### ISSUE TITLE
Triggers don’t work on certain titles

### ISSUE THREAD

**Issue by JDsGod77** [hhd-dev/hhd#68]
Hello, I have a GPD win mini 2024 and certain games aren’t functioning right with the use of the triggers… for example, in both Spider-Man miles morales and Spider-Man remastered the triggers just don’t work at all no input is shown when pushing down the triggers the only way I’ve gotten them to work is by disabling steam input but it’s inconvenient due to the fact that the game still receives input when I’m in the steam menus on bazzite… this problem is also in GTA V, days gone, and X-men origins Wolverine except disabling steam input in those games makes the controller stop working all together… every other game I’ve tried works fine it’s just those games and those are some of my favorite games so it’s unfortunate that this issue is happening with them… any help would be appreciated, thank you

**Comment by antheas** [comment]
I finished remastered 2 weeks ago using steam input with gyro with the dualsense controller and it worked perfectly 

Are you sure?
