### ISSUE TITLE
Powerbutton enabled but still shutting down

### ISSUE THREAD

**Issue by DocMAX** [hhd-dev/hhd#72]
In HHD decky powerbutton is enable, but my Steamdeck still does shutdown.

**Comment by antheas** [comment]
Steamdeck? I disabled it on the steam deck because it breaks the volume buttons

You're supposed to inhibit with systemd and use the valve power button daemon

The gamescope session has the commands

**Comment by antheas** [comment]
Hopefully you figured it out.

**Comment by DocMAX** [comment]
Without this setting in logind.conf the power button still is shutdown down the system (Steam Deck OLED+LCD, NOT GPD WIN 4).
So not sure if this is still a hhd problem...
```
[Login]
HandlePowerKey=ignore
```

**Comment by antheas** [comment]
Your session is broken. It needs to start Valve's power button daemon but it does not.

Do not enable the hhd one. It breaks the volume buttons.

**Comment by DocMAX** [comment]
Ok strange. With my config all works now. Also the volume buttons. No power button daemon installed.

**Comment by antheas** [comment]
The power button of the steamdeck comes out of the AT keyboard and you need Valve's powerbutton daemon to handle it properly + systemd to ignore it.
