### ISSUE TITLE
Gyro always on PS5 controller.

### ISSUE THREAD

**Issue by Globetrotter129** [hhd-dev/hhd#76]
Gyro right stick emulation is always on even while using gyro mouse. 2 gyros at the same time.

Edit: I had to turn off gyro sync in the Handheld Daemon menu.

**Comment by antheas** [comment]
If you have any bindings from legion space, remove them with the factory reset option

**Comment by Globetrotter129** [comment]
> If you have any bindings from legion space, remove them with the factory reset option

I did this and I can now turn it on or off by ticking or unticking gyro sync.

**Comment by antheas** [comment]
Do not disable gyro sync, it will only cause issues. Gyro sync is a compatibility fix, it should not affect how gyro works.

Uninstall the legion go remapper decky plugin if you have it.

**Comment by antheas** [comment]
Hopefully you figured it out.
