### ISSUE TITLE
Minecraft Bedrock Edition NIX Launcher Constant Scrolling 

### ISSUE THREAD

**Issue by davey1343** [hhd-dev/hhd#77]
Device is ROG ALLY.

When using the Bedrock launcher on Bazzite it is not possible to play the game as the HHD input is constantly being read causing continuous scrolling downwards.

**Comment by antheas** [comment]
Can you link the launcher?

**Comment by davey1343** [comment]
https://github.com/minecraft-linux/mcpelauncher-ui-manifest/tree/ng

**Comment by davey1343** [comment]
This is after running the command:

https://photos.app.goo.gl/hNDsUz5qHYAQGJFX7

If I hold command centre to go into mouse mode and move cursor it will stop
but then start again if I move the left stick:
https://photos.app.goo.gl/nyij64otrS8zEPoK6

**Comment by antheas** [comment]
Before you launch the game go into controller settings and disable steam input

See if it still does it

**Comment by davey1343** [comment]
That has stopped it but obviously have no gamepad controls now

**Comment by antheas** [comment]
You should still have controllers work. Steam input only does remapping. If the launcher does not support controllers that's another problem and you need to deal with your steam input profile

**Comment by davey1343** [comment]
Ok.

Steam input off and then rebinding the controls within the launcher and the
issue reappears 😭

**Comment by davey1343** [comment]
I have another input called ' ASUS Keyboard' within the launcher button
binding screen. Could that be the issue?

I'm assuming it's something to do with HHD as my son's steam deck doesn't
have the issue.

**Comment by antheas** [comment]
I've had a similar issue on some games after suspend. They get stuck on left stick in the menus. Haven't figured out why

Probably not the Asus keyboard although it wouldnt be the first time it interfered

**Comment by antheas** [comment]
Do you have a more reputable link for the launcher? I can download it later/tomorrow

Would also be nice to demo it on the steam deck

It's hard to figure out how things should behave when I don't have a steam deck

**Comment by davey1343** [comment]
Ah ok. I'm not mad then. May be useful for solving your resume issue then
as it's a repeatable issue.

**Comment by davey1343** [comment]
It's available on the discover launcher within bazzite

**Comment by davey1343** [comment]
This is on my son's steamdeck:

https://photos.app.goo.gl/AsACkTwric7iw9z89

**Comment by antheas** [comment]
https://flathub.org/apps/search?q=minecraft should be in here somewhere?

**Comment by davey1343** [comment]
Minecraft Bedrock Launcher. 2nd one down

**Comment by antheas** [comment]
Do you need an android license for it?

**Comment by davey1343** [comment]
Ah yes you need Minecraft apk on your Google play account

**Comment by antheas** [comment]
I will look into it these days. I know some other games have a similar issue. For now, I would suggest you try Steam Input disabled with the Xbox emulation profile. I cant promise you a solution this week, so try to find a workaround for now.

if the command you ran worked and you had the issue as well, then its not hhd and its an obscure steam issue. Nevertheless, it should be fixed.

**Comment by antheas** [comment]
I tried various fixes for it and encountered a similar issue in different ways. We are unsure of why it happens. 

We also have had it happen with external controllers without Handheld Daemon running. It is very weird.

**Comment by antheas** [comment]
Perhaps this fixed itself. We have done a lot of work on the matter and input management is a lot more mature now.
