### ISSUE TITLE
Antec Core HS missing 2 Xbox buttons

### ISSUE THREAD

**Issue by clairearmstrong** [hhd-dev/hhd#90]
I am using the KDE Bazzite environment on the Antec Core HS, which is a rebranded Ayaneo Slide.
The Xbox Home and Share buttons are not mapped to anything. There are 3 spare buttons on the Antec that don't seem to do anything on Bazzite

**Comment by antheas** [comment]
`cat /sys/devices/virtual/dmi/id/product_name`

**Comment by clairearmstrong** [comment]
SLIDE

**Comment by antheas** [comment]
`journalctl -b | fpaste`

They really did not even change the product name

**Comment by antheas** [comment]
Ok, here is the command to fix:

```
sudo systemctl enable --now hhd@$(whoami)
```

The slide dmi was missing from Bazzite. It will be added. You can run this command and after verifying everything works close the issue.

**Comment by clairearmstrong** [comment]
I have the RGB on the thumbsticks turned off, but now when I sleep it in Steam the RGB comes on, and the fan is still running. I can't say for definite but I'm fairly sure the fan was off when I slept it earlier today

**Comment by antheas** [comment]
Welcome to the Linux experience on Ayaneo devices. 

You can run the previous command with disable then see if it still happens. Although I am going to be honest with you, the Slide has not been a good experience on Linux.

**Comment by antheas** [comment]
I will probably add a note in the readme so that people are not misled by the supported list meaning linux support.
