### ISSUE TITLE
Use touchscreen as touchpad

### ISSUE THREAD

**Issue by mikeyobrien** [hhd-dev/hhd#97]
Is it possible to use the touchscreen as a touch pad on the rog ally? It's difficult to be precise with touch inputs for UIs not built for a smaller screen.

**Comment by antheas** [comment]
Did you use the mouse mode by holding the ROG button?

**Comment by antheas** [comment]
Hopefully you figured it out. Doing the screen as a touchpad is an option but it wouldnt be the most intuitive.
